name: CI/PR
on:
  pull_request:
  push:
    branches:
      - master
      - validate/*

jobs:
  check_diff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-

    - name: yarn
      run: yarn

    - name: yarn run build
      run: yarn run build

    - name: check for uncommitted changes
      # Ensure no changes.
      run: |
        git add -u . # compare after applying git EOL normalization
        git diff --cached --exit-code --stat \
        || (echo "##[error] found changed files after build. please 'yarn run build'" \
                 "and check in all changes" \
            && git diff --cached \
            && exit 1)

  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-
    - name: yarn
      run: yarn

    - uses: ./
      with:
        service-token: ${{ secrets.RichCodeNavServiceTokenDev }}
        languages: typescript
        repo-token: ${{ github.token }}
        environment: development
        nugetFeed: https://pkgs.dev.azure.com/azure-public/vside/_packaging/vs-buildservices@Local/nuget/v3/index.json
